web_server:
  bind: 0.0.0.0
  port: 8013
  run_v2: true
  web_ui: yes
tasks:
  download-rss:
    rss: $RSS_URL
    all_series: yes
    transmission:
      host: transmission
      port: 9091
    clean_transmission:
      host: transmission
      port: 9091
      finished_for: 1 hours
  sort-files:
    filesystem:
      path: /transmission/
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    seen: local
    thetvdb_lookup: yes
    all_series:
      parse_only: yes
    move:
      to: /shows/{{ tvdb_series_name|default('Unknown') }}/Season {{ tvdb_season|default('Unknown') }}
      rename: "{{ tvdb_series_name|default('Unknown Serie') }}_{{ series_id|default('XX') }}_{{ tvdb_ep_name|default('Unknown Episode Name') }}{{ location | pathext }}"
#    exec:  /usr/local/bin/periscope -l "$SUBTITLES_LANGUAGE" "/shows/{{ tvdb_series_name|default('Unknown') }}/Season {{ tvdb_season|default('Unknown') }}/{{ tvdb_series_name|default('Unknown Serie') }}_{{ series_id|default('XX') }}_{{ tvdb_ep_name|default('Unknown Episode Name') }}{{ location | pathext }}"
    exec:  subliminal download -l "$SUBTITLES_LANGUAGE" "/shows/{{ tvdb_series_name|default('Unknown') }}/Season {{ tvdb_season|default('Unknown') }}/{{ tvdb_series_name|default('Unknown Serie') }}_{{ series_id|default('XX') }}_{{ tvdb_ep_name|default('Unknown Episode Name') }}{{ location | pathext }}"
schedules:
  # Run every task once an hour
  - tasks: '*'
    interval:
      hours: 1
